// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3CDjxZYaykpMpP80fmRoKTcfu79bi4d0',
    appId: '1:916833155639:android:158f5315474b627b45ddb2',
    messagingSenderId: '916833155639',
    projectId: 'biggarbraai',
    authDomain: 'biggarbraai.firebaseapp.com',
    storageBucket: 'biggarbraai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CDjxZYaykpMpP80fmRoKTcfu79bi4d0',
    appId: '1:916833155639:android:158f5315474b627b45ddb2',
    messagingSenderId: '916833155639',
    projectId: 'biggarbraai',
    storageBucket: 'biggarbraai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiq3fKEvloN6s9OrxLYTcvcUzPGUIVNBA',
    appId: '1:916833155639:ios:46d3db745092b16545ddb2',
    messagingSenderId: '916833155639',
    projectId: 'biggarbraai',
    storageBucket: 'biggarbraai.appspot.com',
    androidClientId: '916833155639-up1sf2arqmbiteoknna5g5na4nkrdkbs.apps.googleusercontent.com',
    iosClientId: '916833155639-lj05jnd28ddq18pedmqm85pre7s1ilic.apps.googleusercontent.com',
    iosBundleId: 'com.biggarbraai.shop',
  );
}
